src/Entity/Adress.php
<?php

namespace App\Entity;

use App\Repository\AdressRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdressRepository::class)]
class Adress
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\Column]
    private ?int $number = null;

    #[ORM\Column(length: 255)]
    private ?string $ZipCode = null;

    #[ORM\Column(length: 255)]
    private ?string $Country = null;

    #[ORM\ManyToOne(inversedBy: 'adresses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $Company = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->ZipCode;
    }

    public function setZipCode(string $ZipCode): static
    {
        $this->ZipCode = $ZipCode;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): static
    {
        $this->Country = $Country;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->Company;
    }

    public function setCompany(?Company $Company): static
    {
        $this->Company = $Company;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }
}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Attribute as Vich;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
#[Vich\Uploadable]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\OneToOne(targetEntity: User::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $owner = null;

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'company')]
    private Collection $Users;

    #[ORM\Column(length: 255)]
    private ?string $Contry = null;

    #[ORM\Column(length: 255)]
    private ?string $ActivitySector = null;

    #[ORM\Column(length: 255)]
    private ?string $Size = null;

    #[Vich\UploadableField(mapping: 'company_logo', fileNameProperty: 'logo')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    /**
     * @var Collection<int, Adress>
     */
    #[ORM\OneToMany(targetEntity: Adress::class, mappedBy: 'Company', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $adresses;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    /**
     * @var Collection<int, Invitation>
     */
    #[ORM\OneToMany(targetEntity: Invitation::class, mappedBy: 'company', cascade: ['remove'])]
    private Collection $invitations;

    public function __construct()
    {
        $this->Users = new ArrayCollection();
        $this->adresses = new ArrayCollection();
        $this->invitations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->Users;
    }

    public function addUser(User $user): static
    {
        if (!$this->Users->contains($user)) {
            $this->Users->add($user);
            $user->setCompany($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->Users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getCompany() === $this) {
                $user->setCompany(null);
            }
        }

        return $this;
    }

    public function getContry(): ?string
    {
        return $this->Contry;
    }

    public function setContry(string $Contry): static
    {
        $this->Contry = $Contry;

        return $this;
    }

    public function getActivitySector(): ?string
    {
        return $this->ActivitySector;
    }

    public function setActivitySector(string $ActivitySector): static
    {
        $this->ActivitySector = $ActivitySector;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->Size;
    }

    public function setSize(string $Size): static
    {
        $this->Size = $Size;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Adress>
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adress $adress): static
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses->add($adress);
            $adress->setCompany($this);
        }

        return $this;
    }

    public function removeAdress(Adress $adress): static
    {
        if ($this->adresses->removeElement($adress)) {
            // set the owning side to null (unless already changed)
            if ($adress->getCompany() === $this) {
                $adress->setCompany(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Invitation>
     */
    public function getInvitations(): Collection
    {
        return $this->invitations;
    }

    public function addInvitation(Invitation $invitation): static
    {
        if (!$this->invitations->contains($invitation)) {
            $this->invitations->add($invitation);
            $invitation->setCompany($this);
        }

        return $this;
    }

    public function removeInvitation(Invitation $invitation): static
    {
        if ($this->invitations->removeElement($invitation)) {
            if ($invitation->getCompany() === $this) {
                $invitation->setCompany(null);
            }
        }

        return $this;
    }
}

src/Entity/Invitation.php
<?php

namespace App\Entity;

use App\Repository\InvitationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InvitationRepository::class)]
class Invitation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $token = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $expiresAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'invitations')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Company $company = null;

    #[ORM\ManyToOne]
    private ?QuizTemplate $quizTemplate = null;

    #[ORM\OneToOne(mappedBy: 'invitation', cascade: ['persist', 'remove'])]
    private ?QuizSession $quizSession = null;

    #[ORM\Column(length: 10, options: ['default' => 'email'])]
    private string $type = 'email';

    #[ORM\Column(length: 20, options: ['default' => 'membership'])]
    private string $purpose = 'membership';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(\DateTimeImmutable $expiresAt): static
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getQuizTemplate(): ?QuizTemplate
    {
        return $this->quizTemplate;
    }

    public function setQuizTemplate(?QuizTemplate $quizTemplate): static
    {
        $this->quizTemplate = $quizTemplate;

        return $this;
    }

    public function getQuizSession(): ?QuizSession
    {
        return $this->quizSession;
    }

    public function setQuizSession(?QuizSession $quizSession): static
    {
        // unset the owning side of the relation if necessary
        if ($quizSession === null && $this->quizSession !== null) {
            $this->quizSession->setInvitation(null);
        }

        // set the owning side of the relation if necessary
        if ($quizSession !== null && $quizSession->getInvitation() !== $this) {
            $quizSession->setInvitation($this);
        }

        $this->quizSession = $quizSession;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getPurpose(): string
    {
        return $this->purpose;
    }

    public function setPurpose(string $purpose): static
    {
        $this->purpose = $purpose;

        return $this;
    }

    public function isExpired(): bool
    {
        return $this->expiresAt < new \DateTimeImmutable();
    }
}

src/Entity/QuizTemplate.php
<?php

namespace App\Entity;

use App\Repository\QuizTemplateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuizTemplateRepository::class)]
class QuizTemplate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Mode = null;

    #[ORM\Column(length: 255)]
    private ?string $Type = null;

    #[ORM\Column(nullable: true)]
    private ?int $timeLimit = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Company $company = null;

    #[ORM\ManyToMany(targetEntity: QuizRule::class, inversedBy: 'templates', cascade: ['persist'])]
    private Collection $Rules;

    /**
     * @var Collection<int, Question>
     */
    #[ORM\ManyToMany(targetEntity: Question::class, cascade: ['persist'])]
    private Collection $Questions;

    public function __construct()
    {
        $this->Rules = new ArrayCollection();
        $this->Questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getMode(): ?string
    {
        return $this->Mode;
    }

    public function setMode(string $Mode): static
    {
        $this->Mode = $Mode;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getTimeLimit(): ?int
    {
        return $this->timeLimit;
    }

    public function setTimeLimit(?int $timeLimit): static
    {
        $this->timeLimit = $timeLimit;

        return $this;
    }

    /**
     * @return Collection<int, QuizRule>
     */
    public function getRules(): Collection
    {
        return $this->Rules;
    }

    public function addRule(QuizRule $rule): static
    {
        if (!$this->Rules->contains($rule)) {
            $this->Rules->add($rule);
        }

        return $this;
    }

    public function removeRule(QuizRule $rule): static
    {
        $this->Rules->removeElement($rule);

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->Questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->Questions->contains($question)) {
            $this->Questions->add($question);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        $this->Questions->removeElement($question);

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Form/InvitationType.php
<?php

namespace App\Form;

use App\Entity\Invitation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class InvitationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom', TextType::class, [
                'label' => 'Prénom',
                'constraints' => [new NotBlank(message: 'Le prénom est obligatoire.')],
            ])
            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'constraints' => [new NotBlank(message: 'Le nom est obligatoire.')],
            ])
            ->add('email', EmailType::class, [
                'label' => 'Adresse email',
                'constraints' => [
                    new NotBlank(message: "L'email est obligatoire."),
                    new Email(message: "L'adresse email n'est pas valide."),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Invitation::class,
        ]);
    }
}

templates/quiz/invitation/landing.html.twig
{% extends 'base/base.html.twig' %}

{% block title %}
    {% if invitation.company %}{{ invitation.company.name }} — {% endif %}Invitation au quiz
{% endblock %}

{% block body %}
<div class="min-h-screen bg-slate-50 flex items-center justify-center px-4 py-12">
    <div class="w-full max-w-lg">

        {% if expired %}
            {# Lien expiré #}
            <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-10 text-center">
                <div class="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
                    <twig:ux:icon name="tabler:clock-off" class="w-8 h-8 text-red-400" />
                </div>
                <h1 class="text-xl font-bold text-slate-800 mb-2">Lien expiré</h1>
                <p class="text-sm text-slate-500">Ce lien d'invitation n'est plus valide. Contactez l'entreprise pour obtenir un nouveau lien.</p>
            </div>
        {% else %}

            {# Logo + Nom entreprise #}
            {% if invitation.company %}
            <div class="flex flex-col items-center mb-8">
                {% if invitation.company.logo %}
                    <img
                        src="{{ vich_uploader_asset(invitation.company, 'imageFile') }}"
                        alt="{{ invitation.company.name }}"
                        class="h-20 w-20 object-contain rounded-2xl border border-slate-100 shadow-sm mb-3 bg-white p-1"
                    />
                {% else %}
                    <div class="h-20 w-20 rounded-2xl bg-cyan-600 flex items-center justify-center mb-3 shadow-sm">
                        <twig:ux:icon name="tabler:building" class="w-10 h-10 text-white" />
                    </div>
                {% endif %}
                <h1 class="text-2xl font-bold text-slate-900">{{ invitation.company.name }}</h1>
                {% if invitation.company.description %}
                    <p class="mt-2 text-sm text-slate-500 text-center max-w-xs">{{ invitation.company.description }}</p>
                {% endif %}
            </div>
            {% endif %}

            {# Quiz badge #}
            {% if invitation.quizTemplate %}
            <div class="flex items-center gap-3 p-4 bg-violet-50 border border-violet-200 rounded-xl mb-6">
                <div class="w-10 h-10 rounded-lg bg-violet-600 flex items-center justify-center flex-shrink-0">
                    <twig:ux:icon name="tabler:clipboard-list" class="w-5 h-5 text-white" />
                </div>
                <div>
                    <p class="text-xs text-violet-600 font-medium uppercase tracking-wide">Quiz</p>
                    <p class="text-sm font-bold text-violet-900">{{ invitation.quizTemplate.titre }}</p>
                    <p class="text-xs text-violet-500">{{ invitation.quizTemplate.type }}</p>
                </div>
            </div>
            {% endif %}

            {# Formulaire #}
            <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-8">
                <h2 class="text-lg font-semibold text-slate-800 mb-1">Prêt à commencer ?</h2>
                <p class="text-sm text-slate-500 mb-6">
                    {% if invitation.type == 'email' %}
                        Confirmez vos informations et cliquez sur <strong>Go</strong> pour lancer le quiz.
                    {% else %}
                        Renseignez votre prénom et nom puis cliquez sur <strong>Go</strong> pour lancer le quiz.
                    {% endif %}
                </p>

                <form method="POST" action="{{ path('quiz_invitation_start', {token: invitation.token}) }}" class="space-y-4">

                    <div class="grid grid-cols-2 gap-3">
                        <div class="grid gap-1.5">
                            <label class="text-sm font-medium text-slate-700" for="prenom">Prénom</label>
                            <input
                                type="text"
                                id="prenom"
                                name="prenom"
                                value="{{ invitation.prenom ?? '' }}"
                                {% if invitation.type == 'email' %}readonly{% endif %}
                                required
                                class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 {% if invitation.type == 'email' %}bg-slate-50 text-slate-500 cursor-not-allowed{% endif %}"
                                placeholder="Votre prénom"
                            />
                        </div>
                        <div class="grid gap-1.5">
                            <label class="text-sm font-medium text-slate-700" for="nom">Nom</label>
                            <input
                                type="text"
                                id="nom"
                                name="nom"
                                value="{{ invitation.nom ?? '' }}"
                                {% if invitation.type == 'email' %}readonly{% endif %}
                                required
                                class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 {% if invitation.type == 'email' %}bg-slate-50 text-slate-500 cursor-not-allowed{% endif %}"
                                placeholder="Votre nom"
                            />
                        </div>
                    </div>

                    <button
                        type="submit"
                        class="w-full inline-flex items-center justify-center gap-2 px-6 py-3 bg-cyan-600 text-white text-sm font-semibold rounded-xl hover:bg-cyan-700 transition-colors shadow-sm mt-2"
                    >
                        <twig:ux:icon name="tabler:player-play" class="w-4 h-4" />
                        Go — Lancer le quiz
                    </button>
                </form>
            </div>

            {# Expiration info #}
            <p class="text-center text-xs text-slate-400 mt-4">
                Ce lien expire le {{ invitation.expiresAt|date('d/m/Y à H:i') }}
            </p>

        {% endif %}

    </div>
</div>
{% endblock %}