src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Attribute as Vich;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
#[Vich\Uploadable]
class Question
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titled = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $level = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[Vich\UploadableField(mapping: 'question_image', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @var Collection<int, Answer>
     */
    #[ORM\OneToMany(targetEntity: Answer::class, mappedBy: 'question', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $Reponses;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Company $company = null;

    public function __construct()
    {
        $this->Reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitled(): ?string
    {
        return $this->titled;
    }

    public function setTitled(string $titled): static
    {
        $this->titled = $titled;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getReponses(): Collection
    {
        return $this->Reponses;
    }

    public function addReponse(Answer $reponse): static
    {
        if (!$this->Reponses->contains($reponse)) {
            $this->Reponses->add($reponse);
            $reponse->setQuestion($this);
        }

        return $this;
    }

    public function removeReponse(Answer $reponse): static
    {
        if ($this->Reponses->removeElement($reponse)) {
            if ($reponse->getQuestion() === $this) {
                $reponse->setQuestion(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Entity/QuizSession.php
<?php

namespace App\Entity;

use App\Repository\QuizSessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuizSessionRepository::class)]
class QuizSession
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'quizSessions')]
    private ?User $user = null;

    #[ORM\OneToOne(inversedBy: 'quizSession', cascade: ['persist', 'remove'])]
    private ?Invitation $invitation = null;

    #[ORM\ManyToOne]
    private ?QuizTemplate $quizTemplate = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $startAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endAt = null;

    #[ORM\Column(nullable: true)]
    private ?float $finalScore = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $participantName = null;

    /**
     * @var Collection<int, UserReponses>
     */
    #[ORM\OneToMany(targetEntity: UserReponses::class, mappedBy: 'Session', orphanRemoval: true)]
    private Collection $userReponses;

    public function __construct()
    {
        $this->userReponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getInvitation(): ?Invitation
    {
        return $this->invitation;
    }

    public function setInvitation(?Invitation $invitation): static
    {
        $this->invitation = $invitation;

        return $this;
    }

    public function getQuizTemplate(): ?QuizTemplate
    {
        return $this->quizTemplate;
    }

    public function setQuizTemplate(?QuizTemplate $quizTemplate): static
    {
        $this->quizTemplate = $quizTemplate;

        return $this;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): static
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTimeImmutable $endAt): static
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getFinalScore(): ?float
    {
        return $this->finalScore;
    }

    public function getParticipantName(): string
    {
        if ($this->participantName !== null) {
            return $this->participantName;
        }
        if ($this->getUser()) {
            return (string) $this->getUser()->getUserIdentifier();
        }
        if ($this->getInvitation()) {
            return "Invitation";
        }
        return "Anonyme";
    }

    public function setParticipantName(?string $participantName): static
    {
        $this->participantName = $participantName;

        return $this;
    }

    public function getDurationString(): string
    {
        if (!$this->startAt || !$this->endAt) {
            return 'En cours / Inconnu';
        }
        $diff = $this->startAt->diff($this->endAt);
        return $diff->format('%H h %I min %S s');
    }

    public function setFinalScore(float $finalScore): static
    {
        $this->finalScore = $finalScore;

        return $this;
    }

    /**
     * @return Collection<int, UserReponses>
     */
    public function getUserReponses(): Collection
    {
        return $this->userReponses;
    }

    public function addUserReponse(UserReponses $userReponse): static
    {
        if (!$this->userReponses->contains($userReponse)) {
            $this->userReponses->add($userReponse);
            $userReponse->setSession($this);
        }

        return $this;
    }

    public function removeUserReponse(UserReponses $userReponse): static
    {
        if ($this->userReponses->removeElement($userReponse)) {
            // set the owning side to null (unless already changed)
            if ($userReponse->getSession() === $this) {
                $userReponse->setSession(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        $quizName = $this->quizTemplate ? $this->quizTemplate->getTitre() : 'Quiz supprimé';
        $date = $this->startAt ? $this->startAt->format('d/m/Y H:i') : 'Date inconnue';
        $score = $this->finalScore !== null ? $this->finalScore . '%' : 'N/A';
        return sprintf('%s - %s - Score: %s', $quizName, $date, $score);
    }
}

src/Entity/QuizTemplate.php
<?php

namespace App\Entity;

use App\Repository\QuizTemplateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuizTemplateRepository::class)]
class QuizTemplate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Mode = null;

    #[ORM\Column(length: 255)]
    private ?string $Type = null;

    #[ORM\Column(nullable: true)]
    private ?int $timeLimit = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Company $company = null;

    #[ORM\ManyToMany(targetEntity: QuizRule::class, inversedBy: 'templates', cascade: ['persist'])]
    private Collection $Rules;

    /**
     * @var Collection<int, Question>
     */
    #[ORM\ManyToMany(targetEntity: Question::class, cascade: ['persist'])]
    private Collection $Questions;

    public function __construct()
    {
        $this->Rules = new ArrayCollection();
        $this->Questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getMode(): ?string
    {
        return $this->Mode;
    }

    public function setMode(string $Mode): static
    {
        $this->Mode = $Mode;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): static
    {
        $this->Type = $Type;

        return $this;
    }

    public function getTimeLimit(): ?int
    {
        return $this->timeLimit;
    }

    public function setTimeLimit(?int $timeLimit): static
    {
        $this->timeLimit = $timeLimit;

        return $this;
    }

    /**
     * @return Collection<int, QuizRule>
     */
    public function getRules(): Collection
    {
        return $this->Rules;
    }

    public function addRule(QuizRule $rule): static
    {
        if (!$this->Rules->contains($rule)) {
            $this->Rules->add($rule);
        }

        return $this;
    }

    public function removeRule(QuizRule $rule): static
    {
        $this->Rules->removeElement($rule);

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->Questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->Questions->contains($question)) {
            $this->Questions->add($question);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        $this->Questions->removeElement($question);

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }
}

templates/entreprise/candidates/detail.html.twig
{% extends 'base/base.html.twig' %}

{% set session = invitation.quizSession %}
{% set isCompleted = session and session.endAt is not null %}

{% block title %}
    Résultats — {% if session %}{{ session.participantName }}{% else %}Candidat{% endif %}
{% endblock %}

{% block body %}
<div class="min-h-screen bg-slate-50/50 pt-20">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">

        {# Back button #}
        <a href="{{ path('business_candidates_list') }}"
           class="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800 mb-6 transition-colors">
            <twig:ux:icon name="tabler:arrow-left" class="w-4 h-4" />
            Retour aux candidats
        </a>

        {# Header card #}
        <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 mb-6">
            <div class="flex flex-col sm:flex-row sm:items-center gap-4">

                {# Avatar #}
                <div class="w-14 h-14 rounded-2xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
                    <span class="text-xl font-bold text-cyan-700 uppercase">
                        {% if session %}{{ session.participantName|first }}{% elseif invitation.prenom %}{{ invitation.prenom|first }}{% else %}?{% endif %}
                    </span>
                </div>

                {# Identity #}
                <div class="flex-1">
                    <h1 class="text-xl font-bold text-slate-900">
                        {% if session %}
                            {{ session.participantName }}
                        {% elseif invitation.prenom or invitation.nom %}
                            {{ invitation.prenom }} {{ invitation.nom }}
                        {% else %}
                            Candidat anonyme
                        {% endif %}
                    </h1>
                    {% if invitation.email %}
                        <p class="text-sm text-slate-500 mt-0.5">{{ invitation.email }}</p>
                    {% endif %}
                    <div class="flex items-center gap-2 mt-1">
                        {% if invitation.type == 'link' %}
                            <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-violet-100 text-violet-700">
                                <twig:ux:icon name="tabler:link" class="w-3 h-3" />
                                Lien
                            </span>
                        {% else %}
                            <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-cyan-100 text-cyan-700">
                                <twig:ux:icon name="tabler:mail" class="w-3 h-3" />
                                Email
                            </span>
                        {% endif %}
                    </div>
                </div>

                {# Score block #}
                {% if isCompleted and session.finalScore is not null %}
                    <div class="flex flex-col items-center justify-center px-6 py-4 rounded-xl
                        {% if totalQuestions > 0 and (session.finalScore / totalQuestions) >= 0.7 %}bg-green-50 border border-green-200
                        {% elseif totalQuestions > 0 and (session.finalScore / totalQuestions) >= 0.4 %}bg-amber-50 border border-amber-200
                        {% else %}bg-red-50 border border-red-200{% endif %}">
                        <span class="text-3xl font-black
                            {% if totalQuestions > 0 and (session.finalScore / totalQuestions) >= 0.7 %}text-green-600
                            {% elseif totalQuestions > 0 and (session.finalScore / totalQuestions) >= 0.4 %}text-amber-600
                            {% else %}text-red-500{% endif %}">
                            {{ session.finalScore|number_format(0) }}/{{ totalQuestions }}
                        </span>
                        <span class="text-xs font-medium text-slate-500 mt-0.5">bonnes réponses</span>
                        {% if totalQuestions > 0 %}
                            <span class="text-xs font-bold
                                {% if (session.finalScore / totalQuestions) >= 0.7 %}text-green-600
                                {% elseif (session.finalScore / totalQuestions) >= 0.4 %}text-amber-600
                                {% else %}text-red-500{% endif %}">
                                {{ ((session.finalScore / totalQuestions) * 100)|number_format(0) }}%
                            </span>
                        {% endif %}
                    </div>
                {% endif %}
            </div>

            {# Meta row #}
            <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6 pt-6 border-t border-slate-50">
                <div>
                    <p class="text-xs text-slate-400 font-medium uppercase tracking-wide mb-1">Quiz</p>
                    <p class="text-sm font-semibold text-slate-700">
                        {{ invitation.quizTemplate ? invitation.quizTemplate.titre : '—' }}
                    </p>
                    {% if invitation.quizTemplate %}
                        <p class="text-xs text-slate-400">{{ invitation.quizTemplate.type }}</p>
                    {% endif %}
                </div>
                <div>
                    <p class="text-xs text-slate-400 font-medium uppercase tracking-wide mb-1">Début</p>
                    <p class="text-sm font-semibold text-slate-700">
                        {{ session ? session.startAt|date('d/m/Y') : '—' }}
                    </p>
                    {% if session %}
                        <p class="text-xs text-slate-400">{{ session.startAt|date('H:i') }}</p>
                    {% endif %}
                </div>
                <div>
                    <p class="text-xs text-slate-400 font-medium uppercase tracking-wide mb-1">Durée</p>
                    <p class="text-sm font-semibold text-slate-700">
                        {{ isCompleted ? session.durationString : '—' }}
                    </p>
                </div>
                <div>
                    <p class="text-xs text-slate-400 font-medium uppercase tracking-wide mb-1">Statut</p>
                    {% if isCompleted %}
                        <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-700">
                            <twig:ux:icon name="tabler:circle-check" class="w-3 h-3" />
                            Terminé
                        </span>
                    {% elseif session %}
                        <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                            <twig:ux:icon name="tabler:clock-play" class="w-3 h-3" />
                            En cours
                        </span>
                    {% else %}
                        <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-700">
                            <twig:ux:icon name="tabler:clock" class="w-3 h-3" />
                            En attente
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>

        {# Results by question #}
        {% if resultsByQuestion is not empty %}
            <h2 class="text-lg font-bold text-slate-800 mb-4">Détail des réponses</h2>

            <div class="space-y-4">
                {% set qIndex = 0 %}
                {% for qId, result in resultsByQuestion %}
                    {% set qIndex = qIndex + 1 %}
                    <div class="bg-white rounded-xl border {% if result.isCorrect %}border-green-200{% else %}border-red-200{% endif %} shadow-sm overflow-hidden">

                        {# Question header #}
                        <div class="flex items-start gap-3 p-4 {% if result.isCorrect %}bg-green-50/60{% else %}bg-red-50/60{% endif %}">
                            <div class="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold
                                {% if result.isCorrect %}bg-green-600 text-white{% else %}bg-red-500 text-white{% endif %}">
                                {{ qIndex }}
                            </div>
                            <div class="flex-1 min-w-0">
                                <p class="text-sm font-semibold text-slate-800">{{ result.question.titled }}</p>
                                {% if result.question.level %}
                                    <span class="text-xs text-slate-400 mt-0.5 inline-block">{{ result.question.level }}</span>
                                {% endif %}
                            </div>
                            <div class="flex-shrink-0">
                                {% if result.isCorrect %}
                                    <span class="inline-flex items-center gap-1 text-xs font-medium text-green-700">
                                        <twig:ux:icon name="tabler:circle-check" class="w-4 h-4" />
                                        Correct
                                    </span>
                                {% else %}
                                    <span class="inline-flex items-center gap-1 text-xs font-medium text-red-600">
                                        <twig:ux:icon name="tabler:circle-x" class="w-4 h-4" />
                                        Incorrect
                                    </span>
                                {% endif %}
                            </div>
                        </div>

                        {# Answers #}
                        <div class="p-4 space-y-2">
                            {% set selectedIds = result.selectedAnswers|map(a => a.id) %}
                            {% for answer in result.question.reponses %}
                                {% set isSelected = answer.id in selectedIds %}
                                {% set isCorrectAnswer = answer.isCorrect %}
                                <div class="flex items-start gap-2.5 px-3 py-2 rounded-lg text-sm
                                    {% if isSelected and isCorrectAnswer %}bg-green-50 border border-green-200 text-green-800
                                    {% elseif isSelected and not isCorrectAnswer %}bg-red-50 border border-red-200 text-red-700
                                    {% elseif not isSelected and isCorrectAnswer %}bg-green-50/40 border border-green-100 text-green-700
                                    {% else %}border border-transparent text-slate-500{% endif %}">
                                    <div class="w-4 h-4 mt-0.5 flex-shrink-0">
                                        {% if isSelected and isCorrectAnswer %}
                                            <twig:ux:icon name="tabler:circle-check-filled" class="w-4 h-4 text-green-600" />
                                        {% elseif isSelected and not isCorrectAnswer %}
                                            <twig:ux:icon name="tabler:circle-x-filled" class="w-4 h-4 text-red-500" />
                                        {% elseif not isSelected and isCorrectAnswer %}
                                            <twig:ux:icon name="tabler:circle-dotted" class="w-4 h-4 text-green-500" />
                                        {% else %}
                                            <twig:ux:icon name="tabler:circle" class="w-4 h-4 text-slate-300" />
                                        {% endif %}
                                    </div>
                                    <span class="flex-1">{{ answer.text }}</span>
                                    {% if isSelected %}
                                        <span class="text-xs font-medium {% if isCorrectAnswer %}text-green-600{% else %}text-red-500{% endif %} flex-shrink-0">
                                            {% if isCorrectAnswer %}✓{% else %}✗{% endif %} Sélectionné
                                        </span>
                                    {% elseif isCorrectAnswer %}
                                        <span class="text-xs font-medium text-green-600 flex-shrink-0">Bonne réponse</span>
                                    {% endif %}
                                </div>
                                {% if answer.feedback and (isSelected or isCorrectAnswer) %}
                                    <p class="ml-7 text-xs text-slate-500 italic mt-1 pb-1">{{ answer.feedback }}</p>
                                {% endif %}
                            {% endfor %}
                        </div>

                    </div>
                {% endfor %}
            </div>

        {% elseif session %}
            <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-10 text-center">
                <twig:ux:icon name="tabler:file-unknown" class="w-10 h-10 text-slate-300 mx-auto mb-3" />
                <p class="text-sm text-slate-500">Le détail des réponses n'est pas disponible.</p>
            </div>
        {% else %}
            <div class="bg-white rounded-2xl border border-slate-100 shadow-sm p-10 text-center">
                <twig:ux:icon name="tabler:hourglass" class="w-10 h-10 text-slate-300 mx-auto mb-3" />
                <p class="text-sm text-slate-500">Le candidat n'a pas encore commencé le quiz.</p>
            </div>
        {% endif %}

    </div>
</div>
{% endblock %}